"""Initial migrations

Revision ID: 4d48044b7883
Revises: 
Create Date: 2026-07-06 21:14:42.479242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d48044b7883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_created_at'), 'advisors', ['created_at'], unique=False)
    op.create_index(op.f('ix_advisors_email'), 'advisors', ['email'], unique=True)
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_index(op.f('ix_advisors_team_id'), 'advisors', ['team_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('Uploaded', 'Queued', 'Processing', 'Completed', 'Failed', name='call_status_enum', native_enum=False), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_advisor_id'), 'calls', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_calls_created_at'), 'calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_table('call_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analyses_call_id'), 'call_analyses', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_analyses_created_at'), 'call_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_analyses_id'), 'call_analyses', ['id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_call_id'), 'transcript_segments', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_created_at'), 'transcript_segments', ['created_at'], unique=False)
    op.create_index(op.f('ix_transcript_segments_id'), 'transcript_segments', ['id'], unique=False)
    op.create_table('issue_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('Low', 'Medium', 'High', 'Critical', name='severity_enum', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['call_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_tags_analysis_id'), 'issue_tags', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_issue_tags_created_at'), 'issue_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_tags_id'), 'issue_tags', ['id'], unique=False)
    op.create_index(op.f('ix_issue_tags_severity'), 'issue_tags', ['severity'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_tag_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='appeal_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_tag_id'], ['issue_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_advisor_id'), 'appeals', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_appeals_created_at'), 'appeals', ['created_at'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_issue_tag_id'), 'appeals', ['issue_tag_id'], unique=False)
    op.create_index(op.f('ix_appeals_status'), 'appeals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_status'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_issue_tag_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_created_at'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_advisor_id'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_issue_tags_severity'), table_name='issue_tags')
    op.drop_index(op.f('ix_issue_tags_id'), table_name='issue_tags')
    op.drop_index(op.f('ix_issue_tags_created_at'), table_name='issue_tags')
    op.drop_index(op.f('ix_issue_tags_analysis_id'), table_name='issue_tags')
    op.drop_table('issue_tags')
    op.drop_index(op.f('ix_transcript_segments_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_created_at'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_call_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_call_analyses_id'), table_name='call_analyses')
    op.drop_index(op.f('ix_call_analyses_created_at'), table_name='call_analyses')
    op.drop_index(op.f('ix_call_analyses_call_id'), table_name='call_analyses')
    op.drop_table('call_analyses')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_created_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_advisor_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_advisors_team_id'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_email'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_created_at'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
