"""make_speaker_nullable

Revision ID: 7d6b6ee9d39a
Revises: ee4c3a478879
Create Date: 2026-07-06 22:10:28.264021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6b6ee9d39a'
down_revision: Union[str, Sequence[str], None] = 'ee4c3a478879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcript_segments', 'speaker',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_transcript_segments_created_at'), table_name='transcript_segments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transcript_segments_created_at'), 'transcript_segments', ['created_at'], unique=False)
    op.alter_column('transcript_segments', 'speaker',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
