"""Add upload details to Call model

Revision ID: ee4c3a478879
Revises: 4d48044b7883
Create Date: 2026-07-06 21:24:29.562316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4c3a478879'
down_revision: Union[str, Sequence[str], None] = '4d48044b7883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('calls', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('calls', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('calls', sa.Column('file_size_bytes', sa.Integer(), nullable=False))
    op.alter_column('calls', 'duration_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('calls', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('calls', 'duration_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('calls', 'file_size_bytes')
    op.drop_column('calls', 'mime_type')
    op.drop_column('calls', 'stored_filename')
    op.drop_column('calls', 'original_filename')
    # ### end Alembic commands ###
